import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { email, topic, notes, messages } = await request.json();

    if (!email || !email.includes('@')) {
      return NextResponse.json(
        { error: 'Valid email required' },
        { status: 400 }
      );
    }

    // Format notes for email
    const notesHtml = notes.map((note: any) => `
      <div style="margin: 10px 0; padding: 10px; background: #f5f5f5; border-left: 4px solid #8b5cf6;">
        <strong style="color: #8b5cf6;">${note.type.toUpperCase()}</strong>
        <p style="margin: 5px 0;">${note.content}</p>
      </div>
    `).join('');

    const conversationHtml = messages.map((msg: any) => `
      <div style="margin: 15px 0;">
        <strong style="color: ${msg.role === 'user' ? '#2563eb' : '#8b5cf6'};">
          ${msg.role === 'user' ? '👤 You' : '🤖 AI Tutor'}:
        </strong>
        <p style="margin: 5px 0; padding: 10px; background: #f9f9f9; border-radius: 8px;">
          ${msg.content}
        </p>
      </div>
    `).join('');

    const htmlBody = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Your AI Tutor Session Notes</title>
      </head>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; color: white; text-align: center;">
          <h1 style="margin: 0;">🎓 AI Voice Tutor</h1>
          <p style="margin: 10px 0 0 0;">Session Notes</p>
        </div>
        
        <div style="background: white; padding: 30px; margin-top: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
          <h2 style="color: #8b5cf6;">Topic: ${topic}</h2>
          <p style="color: #666;">Date: ${new Date().toLocaleDateString()}</p>
          
          <h3 style="color: #8b5cf6; margin-top: 30px;">📝 Key Notes</h3>
          ${notesHtml}
          
          <h3 style="color: #8b5cf6; margin-top: 30px;">💬 Conversation Summary</h3>
          ${conversationHtml}
        </div>
        
        <div style="text-align: center; margin-top: 20px; color: #666; font-size: 12px;">
          <p>Generated by AI Voice Tutor</p>
          <p>Keep learning and stay curious! 🚀</p>
        </div>
      </body>
      </html>
    `;

    // In production, use a service like SendGrid, Resend, or AWS SES
    // For now, just log it (you'll need to configure an email service)
    console.log('Email would be sent to:', email);
    console.log('Email HTML:', htmlBody);

    // Simulate success (replace with actual email sending)
    return NextResponse.json({
      success: true,
      message: 'Notes prepared for email',
      // In production, add actual email sending here
      note: 'Email service not configured. Check server logs for HTML output.'
    });

  } catch (error) {
    console.error('Email notes error:', error);
    return NextResponse.json(
      { error: 'Failed to process email request' },
      { status: 500 }
    );
  }
}
